### ISSUE TITLE
I get the C10_inception_moments.npz,but there still have some problem :tarfile.ReadError: not a gzip file

### ISSUE THREAD

**Issue by Luobuyao** [WANG-Chaoyue/EvolutionaryGAN-pytorch#1]
I get the C10_inception_moments.npz,but there still have some problem :tarfile.ReadError: not a gzip file

**Comment by qq272574497** [comment]
> I get the C10_inception_moments.npz,but there still have some problem :tarfile.ReadError: not a gzip file

can you give me C10_inception_moments.npz?

**Comment by Adapter525** [comment]
请问你最后怎么解决的 呀
